app/controllers/web_controller.rb, app/views/web/vbms_failure.html.erb
This puts the error less on the user, and more on VBMS. Retrying the
same page (by refreshing or clicking the href) should restart the
caseflow workflow, since we're not sure the state that things have been
left in.
=> If VBMS is down, return a helpful error (Close: #25)

app/views/web/generate.html.erb
Fixes #86
Highlights
- Go back text in initial description
- Go back text at botton
- Right alignment of upload button
=> Added back options to generate page, fixes #86

README.markdown
Changing 
> rvm use jruby-1.7.22
> source env.sh
to 
> source env.sh
And modifying sentence before it to remove RVM-related language.
=> Removing an RVM reference since we're using rbenv

lib/sources/caseflow/reports.rb
Previously we included a case if their eFoler contained any documents at all. With this change we include a case if they have an eFolder _and_ it contains at least one appeals related document (NOD, SOC, SSOC, Form8, Form9)
=> Change the criteria for the seam report:

app/assets/javascripts/application.js, app/assets/stylesheets/application.css.scss, app/views/web/_form8_text.html.erb, app/views/web/_form8_two_radio.html.erb, app/views/web/_form8_yes_no_radio.html.erb, app/views/web/questions.html.erb
Simplifying javascript that shows related field based on the selected option.
- Listens for change events on `fieldset` elements
- Uses a `data-showwhen` attribute to form fields
- Uses `hidden` attribute (with CSS for older browsers) for more consistent behavior with assistive tech
=> Linked form items

app/assets/stylesheets/application.css.scss, app/views/web/error.html.erb, app/views/web/generate.html.erb, app/views/web/questions.html.erb, app/views/web/start.html.erb, config/routes.rb
For #256 
Start:
Questions:
Generate:
Known issue: On generate, the buttons and link get split across lines in a wonky way when the screen width is shrunk, but everything is still readable and clickable. Can fix this later if a priority.
@KHarshawat or @maryannbrody : Can one of you review for design?
@webinista or @paultag : Can one of you review code?
=> Add can't certify link to start, questions, and generate pages. Fixes #256.

app/assets/javascripts/application.js
I suggest merging #366 before this one. They work independently of each other. However #364 includes a small UX improvement that affects the behavior of this commit. 
Specifically, there's an invisible area on each side of the modal's content box that _looks like it should be_ clickable, but isn't. #364 eliminates those areas.
=> Adding modal closure on click, Esc feature. closes #364

app/views/layouts/basic.html.erb
- Removing Bootstrap since we're not using it.
- Also removing jQuery 1.9 since we're using v1.11.3
=> Removing bootstrap.min.js and extra call to jQuery 1.9. closes #210

app/assets/stylesheets/application.css.scss, app/views/web/_form8_date.html.erb, app/views/web/_form8_textarea.html.erb, app/views/web/questions.html.erb
- Adding max width for textarea wrappers and text input wrappers.
- Changing form8-date-input to form8-text-input. Why add an extra class?
- Changing row class to more descriptive cf-form-textarea-wrap
- Removing cf-wrap-flex because we're not using it.
=> Resizing text field and textarea widths. closes #390

app/assets/stylesheets/application.css.scss, app/views/web/start.html.erb
- Also adding some usage notes re: class names.
Most of these line changes are spacing-related. Key deletions are line 7 (`-<div id="certifications-start">`) and 71 of `app/views/web/start.html.erb`
=> Removing <div> that caused spacing issue on start. Closes #393

app/assets/stylesheets/application.css.scss, app/views/layouts/basic.html.erb
Making the name less-specific for two reasons:
1. Trying to create a naming system with a cf- prefix
2. Provides a base class and styles that we can build on to for
a `cf-notice--maintenance`, etc. if necessary
=> Changing name of pilot-warning class to cf-notice. closes #389

app/views/web/generate.html.erb
Also adds modal to the `generate` view, however, this probably isn't the best approach. See #422 for more.
=> Adding cf-app-segment class. closes #404

app/assets/stylesheets/application.css.scss, app/views/layouts/basic.html.erb
Footer links retain `:visited` state added by the USWDS. Also changes `p` to `div` because the USWDS automatically adds an underline to every `a` within a `p` element.
=> Make :visited state for action links in app body blue. closes #378

app/assets/stylesheets/application.css.scss, app/views/web/generate.html.erb
Bringing class name in line with new naming convention.
=> Changing .embedded-document class name to .cf-doc-embed. closes #421

app/assets/stylesheets/application.css.scss, app/views/web/_cancel_cert_modal.html.erb
Using usa-button and usa-button-secondary patterns/class names
from the USWDS.
=> Removing cf-btn-faux* class names. closes #431.

app/assets/stylesheets/application.css.scss, app/views/web/404.html.erb, app/views/web/certify.html.erb, app/views/web/error.html.erb, app/views/web/not_found.html.erb, app/views/web/vbms_failure.html.erb
- Changed vbms_failure.html.erb template.
- Added .cf-msg-screen-text class to CSS.
- Changed cf-text-center class to .cf-msg-screen-text in other templates.
Changes to be committed:
modified:   app/assets/stylesheets/application.css.scss
modified:   app/views/web/404.html.erb
modified:   app/views/web/certify.html.erb
modified:   app/views/web/error.html.erb
modified:   app/views/web/not_found.html.erb
modified:   app/views/web/vbms_failure.html.erb
=> Re-styling VBMS Failure page. closes #253

lib/sources/caseflow/reports.rb
The NOD is visible in the VACOLS UI, which allows a user to identity which appeal a given row is
=> Include the NOD date in the reports

app/views/web/generate.html.erb, app/views/web/start.html.erb
Removing `btn` and `btn-primary` classes from generate, start views that were leftover from Bootstrap.
=> Removing `btn` and `btn-primary` classes. closes #455

app/assets/stylesheets/application.css.scss, app/views/web/_form8_checkbox_column.html.erb, app/views/web/_form8_radio_inputs.html.erb, app/views/web/questions.html.erb
Closes #400 
- Resetting margin on `p` elements
- Adding CSS to override margins added to input fields by USWDS
- Adding wrapper `div` around radio options in `app/views/web/questions.html.erb`
- Changing `checkbox` class name to `cf-form-checkbox`
=> Setting 20px spacing between each question

app/assets/javascripts/application.js, app/views/web/_form8_radio_inputs.html.erb, app/views/web/questions.html.erb
Fixed a bug that cleared the `value` attribute for all inputs.
Changed that to clear the value for text, textarea inputs, and
uncheck the radio button and checkboxes.
=> Ensure that values for 8A, 8B, 10B are captured. closes #504

README.markdown
None of those test urls work unless you login as the correct user. Noting that in the README.
=> Add missing step to using test mode

app/controllers/web_controller.rb
My guess is this changed in bc2c50e88c12076d9463fdaa2741636188ba565c and we never updated the front-end.
Wild guess, though.
This is a massive hack and adds tech debt. We need to refactor this. We're now defining this on the labels on the front-end and also on the backend before sending to the Form 8.
=> Add a hacky workaround for incoming 8A data
