- README.markdown
> Updated JRuby version number error in README

- app/assets/stylesheets/application.css.scss
- app/views/layouts/basic.html.erb
> Use a bootstrap nav bar and offer a logout link in it.

- app/assets/stylesheets/application.css.scss
> Navbar 508 compliance fix, fixes #62

- app/assets/stylesheets/application.css.scss
- app/views/layouts/basic.html.erb
> 508 navbar fix

- app/models/case.rb
- app/views/layouts/application.html.erb
> Handle when a PoA is nil

- app/assets/stylesheets/application.css.scss
- app/views/layouts/basic.html.erb
- app/views/web/_form8_text.html.erb
- app/views/web/_form8_two_radio.html.erb
- app/views/web/questions.html.erb
> Fixed #79 -- better explain what the questions are for.

- app/views/layouts/application.html.erb
> make this column slightly wider

- app/assets/stylesheets/application.css.scss
- app/views/web/login.html.erb
Bring it up side-by-side on medium and large screens, and move it back
to how it was when we're on a small size screen.
> Reflow the login form to be inline (Close #71)

- app/assets/javascripts/application.js
closes #183
modified:   app/assets/javascripts/application.js
> Checking existence of #question-form before calling functions

- .travis.yml
everything we do goes through a PR, so we can just build it as a PR, rather than as a branch and a PR.
> Only build master, not other branches

- app/assets/stylesheets/application.css.scss
- app/views/web/start.html.erb
Adds spacing around alert box, form at bottom of page.
> Spacing issues on start page. closes #206

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.erb
- app/views/layouts/basic.html.erb
Ensuring that dropdown closes when the user clicks elsewhere
> 208 dropdown close

- app/assets/stylesheets/application.css.scss
- app/views/web/_form8_checkbox_column.html.erb
- app/views/web/_form8_text.html.erb
- app/views/web/_form8_two_radio.html.erb
- app/views/web/questions.html.erb
- Adds required field indicators and attribute where needed. 
- Closes #80 
- Closes #81 
- Closes #156
> Form 8 changes

- app/assets/javascripts/application.js
- app/views/web/questions.html.erb
Removes piece of JS that controls showing / hiding of form fields. Removes `hidden` attribute from those fields.
> resolves #257 Removing show/hide functionality for form fields.

- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.erb
Change to CSS and `application.html.erb` view
> Adjusting height/width of copy icon to resize button. closes #238

- app/assets/stylesheets/application.css.scss
Collapses .usa-cf_app-segment--v-pad, .usa-cf_app-segment--h-pad, and .usa-cf_app-segment--alt into .usa-cf_app-segment--alt. 
Also WIP for #155.
> Consolidates .usa-cf_app-segment--* classes. closes #222

- app/assets/stylesheets/application.css.scss
- app/views/web/certify.html.erb
Incorporates changes in PR #246. If this is merged first,
okay to close #246 without merging.
> Congratulations screen changes. Solves #155

- app/views/web/error.html.erb
Actual styles attached to these class names are bundled in PR #246
> Adding markup, class names to error page. Closes #248

- app/views/web/generate.html.erb
Style declarations are in #246, but it's OK if this gets merged first.
> Restyling review / generate page. Closes #199

- app/views/web/login.html.erb
> Added descriptive login text, closes #259

- app/models/case.rb
- app/models/fakes.rb
For #277 
Tested with fakes user `full-form8`
> Uses RO Notification date for Form 8 5B, 6B, 7B. Closes #277.

- app/views/web/error.html.erb
Thought I had commited this, but forgot.
Already approved via PR #278 as part of #256, so will merge when build is done.
> Content change that got missed

- app/assets/stylesheets/application.css.scss
- app/views/web/login.html.erb
> Added password placeholder text, closed #260

- app/views/web/questions.html.erb
> Change population logic, add formatting (Closes #295)

- app/models/case.rb
- app/models/fakes.rb
- app/views/web/questions.html.erb
> Use bfdrodec date helpers to encode (Close #293)

- app/views/web/certify.html.erb
'You can now close this page' becomes 'You can now close this browser window'.
> Changing instructional text for user. closes #301

- app/views/web/questions.html.erb
> 10B and 10C always display

- README.FRONTEND.md
- app/views/layouts/basic.html.erb
Removing a link to Clipboard.js that caused it to be linked to and requested twice.
> Only include Clipboard.js once

- app/assets/javascripts/application.js
> Clearing other field if check mark is unchecked after being checked.

- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.erb
- app/views/layouts/basic.html.erb
- app/views/web/generate.html.erb
- app/views/web/login.html.erb
- app/views/web/questions.html.erb
- app/views/web/start.html.erb
> Switching to cf-app-segment, cf-push-left, and cf-push-right.

- Gemfile
- Gemfile.lock
This nokogiri release includes security fixes.
> Bumped nokogiri and brakeman.

- app/views/web/start.html.erb
> Changing "This case cannot be certified" to "Cancel certification"

- app/assets/stylesheets/application.css.scss
- app/views/web/start.html.erb
Adds `.cf-btn-faux`, `.cf-btn-faux--secondary` classes that make links mimic the look of buttons.
> Changing style of "Yes, I'm sure" button. closes #395

- .travis.yml
- Gemfile
- Gemfile.lock
Thanks to @dreid for pointing this out.
> Use bundle audit to make sure our deps are always up to date

- app/assets/stylesheets/application.css.scss
Changes `#2e8540;` to its SCSS variable `$color-green;`
> Changing CSS colors to USWDS variables. closes #458

- app/assets/stylesheets/application.css.scss
- .border-bottom
- .success
- .error
- .navbar-default
- .col-no-right-pad > .col
> Removing extraneous class names

- app/assets/stylesheets/application.css.scss
- app/views/web/login.html.erb
- USWDS markup is more efficient, especially with a `p` tag.
> Removing  #login-login-button ruleset, markup.

- app/models/fakes.rb
- test/helpers/reports_test.rb
Just verifies that calling their spreadsheet_cells method doesn't error
> Added very simplistic tests for reports.

- app/views/web/generate.html.erb
- Change title to “Review Form 8” (Delete “before upload”)
- Change instructions to, “Review the completed Form 8. If the form looks correct, click Upload and certify and the form will automatically be uploaded into VBMS."
- Change button to “Upload and certify” (lowercase “c”)
> Updating generate page text. closes #476

- scripts/png.sh
If you had a space in your path, god only knows what would happen.
> Make this script shellcheck clean.

- app/views/layouts/basic.html.erb
> Load the fonts we want from Google fonts

- app/assets/stylesheets/application.css.scss
- app/views/layouts/basic.html.erb
- Adds "Send feedback" link to drop down menu.
- Updates menu URLs to use ERB-style links.
> Updating styles for drop down menu. closes #235

- app/assets/stylesheets/application.css.scss
The predominant style appears to be 4 spaces, so I normalized to that. Also removed a few tabs.
> Make CSS be indented consistently.

- .travis/pa11y.sh
- app/controllers/web_controller.rb
- app/views/web/help.html.erb
It has instructions on how to log in, so this seems useful. Also run it through the 508 test test.
> Make the help page accessible without being logged in

- lib/sources/caseflow/reports.rb
> Fixes #532 -- add the ability to exclude specific BFKEYs from reports

- app/assets/javascripts/application.js
- app/views/web/_help_text.html.erb
- config/initializers/assets.rb
Also moved dropdown code towards top of CSS file to fix a cascade issue.
Removed unused CSS.
> Fixing placement of navigation drop down. Closes #546.
